### ISSUE TITLE
Does it work on MS Ege?

### ISSUE THREAD

**Issue by wolfgangschneider** [jsakamoto/Toolbelt.Blazor.SpeechRecognition#4]
HI The sample Application (server) works with chrome om my machine but not with Edge. 
The page has access to mic,  Edge version is Version 90.0.818.49 (Official build) (64-bit)

After clicking Start the SpeechRecognition calls imeadetly the end event

B.R Wolfgang

**Comment by jsakamoto** [comment]
Unfortunately, it doesn't work on Microsoft Edge. (even it is Chromium-based.)
Speech Recognition API on a Web browser is just supported by Chrome only.

See also: https://caniuse.com/speech-recognition

**Comment by wolfgangschneider** [comment]
thanks
