### ISSUE TITLE
DisableClientScriptAutoInjection is get only

### ISSUE THREAD

**Issue by WeiYuKiwiplan** [jsakamoto/Toolbelt.Blazor.SpeechRecognition#5]
as title said trying to set DisableClientScriptAutoInjection

builder.Services.AddSpeechRecognition(options =>
{
    // If you don't want automatic injection of js file, add bellow;
    options.DisableClientScriptAutoInjection = true;
});

getting following error
Property or indexer 'SpeechRecognitionOptions.DisableClientScriptAutoInjection' cannot be assigned to -- it is read only

**Comment by jsakamoto** [comment]
@WeiYuKiwiplan Oooh, it's my falt! I'll fix it as soon as possible. Thank you for letting me know that!

**Comment by jsakamoto** [comment]
@WeiYuKiwiplan 
Could you try the latest version of the "Blazor Speech Recognition" NuGet package?

See also: https://www.nuget.org/packages/Toolbelt.Blazor.SpeechRecognition/0.0.5-alpha#releasenotes-body-tab

**Comment by WeiYuKiwiplan** [comment]
@jsakamoto yep that's fixed. thanks for the quick response.

**Comment by jsakamoto** [comment]
@WeiYuKiwiplan It was your contributions! If you didn't contact me, this package might be left as-is. Thank you for your assistance!
